version: "3"
services:
  flask-app:
    image: flask-app
    ports:
      - "5000:5000"
    environment: 
      ENV_FILE_LOCATION: .env
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGO_ADMIN_USER: root
      MONGO_ADMIN_PASS: Secret
    links: 
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment: 
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: Secret